version: "3.8"

services:
  server:
    build:
      context: ./server
    # Uncomment and configure the following lines if you need these services
    # depends_on:
    #   - mongodb
    #   - redis
    # environment:
    #   - MONGO_URI=mongodb://mongodb:27017/yourdbname
    #   - REDIS_URL=redis://redis:6379

  client:
    build:
      context: ./client
    # Assuming the client service doesn't need to expose ports directly
    # as Caddy will act as a reverse proxy
    depends_on:
      - server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

    #  redis:
    #image: redis
    #ports:
    #  - "6379:6379"
